// my-app/config/contracts.ts

export const CONTRACT_IDS = {
    ESCROW: 'CCDJXQS3DFU2VBFAXMXILXFEQZL5NMHPW3N34F2KAGZQBKBKYLPKTLTF',
    MARKETPLACE: 'CBW3HAGIKRUFGINW5JCAGFL53VKMDACLEZNGX7CRM4U7TPHFV5TV4FKY',
    PROPERTY: 'CAEL22JRFVKB3KKQS3DCO2QMLRLXPZNIWZO2ML2V6YJSQWIV77BDF4G3',
    SHARES: 'CA2NYIP3WXHW3UGDQMLXEMMJAO7GXDLFGOWICLLU6DOGU64NFBF7FEHX',
    INCREMENT: 'CDM2IJCM3KAZBEM2SC3VKJ7PZTFKXQXFEEKAODQZVONDRHC3U6HEAWKZ'
  };
  
  export const NETWORK_PASSPHRASE = 'Test SDF Network ; September 2015';
  export const NETWORK_URL = 'https://horizon-testnet.stellar.org';